### ISSUE TITLE
After trying a lot still i am facing following error

### ISSUE THREAD

**Issue by dharmdeep** [StartBootstrap/sb-admin-angular#1]
Hello sir, 
               npm start command giving error like  An unhandled exception occurred: Unknown browser query `basedir=$(dirname "$(echo "$0" | sed -e 's`. Maybe you are using old Browserslist or made typo in query.

I attached the screenshot also. Any help will be highly appreciated.
I used ng update & updated also angular cli, ng rx & yarn but still this error is coming.

![image](https://user-images.githubusercontent.com/7457022/74097403-9f851080-4b31-11ea-85da-04752d1b5181.png)

**Comment by initplatform** [comment]
Hello, try removing the comments in the beginning of the browserlist file. Anything that begins with a `#`

**Comment by initplatform** [comment]
Also note we just did a 1.1.0 release today with Angular 9 as well as added in schematics (See the new README), plus removed the comments from the browserlist file

**Comment by dharmdeep** [comment]
Great issue resolved.

Thanks @initplatform 😊
